services:
  db:
    image: mongo:8.0.3
    container_name: mongo_db
    ports:
      - '6000:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pgsotos
      - MONGO_INITDB_ROOT_PASSWORD=alegrareto
